name: CI/CD (Build, Test & Infra Deploy)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-test-deploy:
    name: Build, Test & Deploy Infra
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: |
          yarn workspace api test
          yarn workspace infra test
          yarn workspace ingest test

      - name: Build services & infra
        run: |
          yarn workspace api build
          yarn workspace ingest build
          yarn workspace front-end build
          cd infra && yarn build

      - name: Configure AWS credentials
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-central-1

      - name: Deploy CDK stacks
        if: github.event_name == 'push'
        run: |
          cd infra
          npx cdk deploy --all --require-approval never
